# Programa de clase

## Antecedentes
A lo largo de la historia, la búsqueda de soluciones ante los grandes retos sociales, económicos y ambientales de la humanidad ha estado íntimamente relacionada con el concepto de innovación. La evolución de cómo las sociedades definen la innovación coincide con la forma en que las mismas entienden la naturaleza de los retos del desarrollo. 
Así como antes de concebir y medir el progreso desde una perspectiva del desarrollo humano, las sociedades utilizaban medidas eminentemente económicas como el Producto Interno Bruto, la innovación se concebía desde una óptica exclusivamente de investigación y desarrollo para la comercialización de productos nuevos. 

El Informe sobre Desarrollo Humano del Programa de las Naciones Unidas para el Desarrollo 2020 “La próxima frontera: El desarrollo humano y el Antropoceno” apoya la hipótesis de que la capacidad de actuación y el empoderamiento de las personas pueden impulsar las medidas necesarias para que vivamos en equilibrio con el planeta y en un mundo más justo. El Informe pone de manifiesto que nos encontramos en un momento sin precedentes en la historia, en el que la actividad humana se ha convertido en una fuerza dominante que afecta a los procesos clave del planeta. Estos efectos interactúan con las desigualdades existentes y amenazan con revertir el desarrollo de manera significativa. El informe también plantea que para cambiar esta trayectoria se requiere una gran transformación en nuestra forma de vivir, trabajar y cooperar. 

Este planteamiento coincide con el surgimiento de una corriente de pensamiento emergente que contempla que las políticas públicas de innovación deben seguir una lógica de proceso de investigación a un nivel sistémico guiado por objetivos sociales y ambientales que busquen no solo reparar los fallos de dirección, coordinación de políticas públicas, articulación de la demanda y reflexión. Esta nueva corriente se conoce como innovación transformativa.

## Sobre _Introducción a la innovación_
Esta clase se enfocará en sentar la innovación como un campo de acción estratégico para crear propuestas de valor que contribuyan a la transformación de los sistemas de negocios, sector público y de impacto social necesaria para la consecución de la agenda 2030 y los Objetivos del Desarrollo Sostenible. El curso explorará los fundamentos de la innovación a través de una revisión del marco teórico sobre la innovación (1) a nivel teórico a través del desarrollo humano y la transformación sistémica y (2) a nivel práctico a través de la aplicación de herramientas para la creación de propuestas de valor innovadoras en diferentes áreas de impacto: corporativa, pública y de impacto social. 

Esto se hará con base en la la investigación y discusión sobre las características individuales y organizacionales requeridas para desarrollar innovación y la producción creativa. La clase utilizará artículos científicos relevantes al tema, recursos audiovisuales y herramientas tecnológicas para estudiar cómo las personas, las organizaciones y las sociedades crean propuestas de valor para el desarrollo sostenible y a la transformación de los sistemas. Finalmente, se desarrollará un proyecto para la aplicación de estos conceptos.

## Resultados esperados

Al finalizar este curso, el alumno habrá:

* Conocido la definición, fundamentos históricos y teóricos sobre la innovación para identificar la innovación desde un enfoque multidimensional que considere aspectos económicos, sociales, culturales y ambientales.
* Identificado cómo las personas, las organizaciones y las sociedades accionan la innovación en diferentes campos de investigación, mercados y en la solución a problemas del desarrollo y la transformación de sistemas.
* Aplicado técnicas y herramientas de innovación para el diseño de negocios o iniciativas de impacto social.

## Estrategia metodológica
Las principales estrategias metodológicas es esta cátedra serán las clases expositivas, lectura de artículos y ensayos académicos, revisión de materiales bibliográficos multimedia (videos), investigación activa de recursos en línea, actividades de entrevista para la investigación de campo y talleres prácticos sobre el pensamiento de diseño (design thinking) y diseño de propuestas de valor.

## Contenido

- Nociones básicas sobre la innovación
  - Conceptos generales de la innovación
  - Complejidad y problemas enredados
  - Áreas de impacto de la innovación
  - Innovación integrada
  - Tecnología e innovación
- Innovación y sociedad
  - El valor del diseño en la innovación
  - La creación de propuestas de valor innovadoras
  - La innovación desde las organizaciones 
  - Incubación y aceleración de la innovación
  - Innovación abierta
  - Los ecosistemas de innovación
- Innovación en acción
  - Modelos de negocio innovadores
  - Innovación centrada en las personas
  - Prototipando la innovación 
  - Comunicando la innovación

## Evaluación

La metodología de evaluación del curso se basará en los siguientes componentes:

- Participación (15%) - Individual: Con el objetivo de incentivar la participación activa y propositiva de los alumnos, se ponderarán las intervenciones en las discusiones del material presentado de forma sincrónica y asincrónica, así como de las lecturas y otros recursos de la clase. La participación puede tomar lugar en las discusiones en vivo, así como en los diversos canales digitales habilitados para el curs. 
- Anteproyecto de innovación (25%) - Grupal: En preparación al proyecto de innovación final, los estudiantes deberán preparar un anteproyecto donde seleccionen una innovación preexistente extraída de un repositorio de innovaciones (p. ej.: Appropedia), justificar su elección con base a una investigación sobre el potencial para la creación de valor (comercial o social) de innovaciones similares. (Los grupos serán de mínimo 4 personas, máximo 5). 
- Actividades multimedia (20%) - Individual: Cada estudiante deberá generar un producto multimedia (Blog, podcast, video explicativo, mapa interactivo o cualquier otra de su preferencia) donde analice la propuesta de valor de una innovación de su elección (producto o servicio comercial, iniciativa social o innovación de base). Esta actividad podrá entregarse en cualquier momento antes de la finalización de la cátedra. 
- Proyecto de innovación (40%) - Grupal: Con base al anteproyecto presentado, los estudiantes desarrollarán y documentarán un proyecto de innovación en Appropedia, un repositorio abierto de proyectos de sostenibilidad.

## Normas generales de la ESEN 
1. Puntualidad: las actividades académicas deberán iniciarse a la hora programada. Al retomarse las clases presenciales, regirá el artículo 22 del Reglamento Académico de la ESEN. 
1. Evaluación de trabajos o informes escritos: con el fin de velar por la excelencia académica en la presentación de documentos escritos, se tomará en cuenta, además del contenido de los mismos, la redacción, la ortografía y la forma de citar las referencias bibliográficas, las cuales deberán seguir los lineamientos del Manual de estilo de la ESEN o APA. El profesor explicará sus expectativas al respecto. 
1. Presentaciones orales de trabajos: se deberá tomar en cuenta, además del contenido de los mismos, la síntesis de ideas en lo que se proyecte, la ortografía y el cumplimiento del tiempo asignado. Cada profesor puede agregar otros aspectos a evaluar si así lo desea, los cuales deberán ser comunicados a los estudiantes oportunamente. Por ejemplo, se podrían evaluar de la siguiente manera: síntesis de ideas, 10 %; ortografía, 10 %; manejo del tiempo, 10 %; contenido, 70 %. Además, el código de vestimenta para este tipo de presentaciones debe mostrar respeto a la audiencia, evitando el uso de elementos que distraigan el desarrollo de la actividad académica. Cada profesor podrá indicar sus expectativas al respecto.
1. Revisión de exámenes: La revisión se deberá solicitar mediante la presentación del formulario y del documento evaluado, en el Registro Académico dentro del plazo de los cinco días posteriores al de la comunicación de los resultados. Si la comunicación se efectúa cuando los alumnos se encuentren en un período de vacaciones, el plazo empezará a correr el primer día hábil en el cual se reanuden las actividades académicas. (Reglamento Académico. Art 32).

## Bibliografía del curso

Estos son algunos de los recursos utilizados en clases anteriores.

- Adam, I. (2016). What Would McLuhan Say about the Smartphone? Applying McLuhan’s Tetrad to the Smartphone. Glocality, 2(1), 3. https://doi.org/10.5334/glo.9
- Anil Gupta: India’s hidden hotbeds of invention—YouTube. (n.d.). Retrieved August 8, 2021, from https://www.youtube.com/watch?v=JHk9YVjhk7c
- Asociación DAG. (2019, August 16). Massimo Menichinelli: Deseño aberto para comunidades: procesos, organizacións, redes. https://www.youtube.com/watch?v=ABlE9TKiORU
- Benkler, Y. (2016). Peer production and cooperation. In Handbook on the Economics of the Internet. Edward Elgar Publishing.
- Berinato, S. (2014, September 5). A Framework for Understanding VUCA. Harvard Business Review. https://hbr.org/2014/09/a-framework-for-understanding-vuca
- Briede W, J. C., & Mora, M. L. (2016). Diseño y Co-Creación Mediante Aprendizaje y Servicio en Contexto Vulnerable: Análisis de Percepción de la Experiencia. Formación Universitaria, 9(1), 57–70. https://doi.org/10.4067/S0718-50062016000100007
- Bunting, M. (2011, November 10). Small is beautiful – an economic idea that has sadly been forgotten | Madeleine Bunting. The Guardian. http://www.theguardian.com/commentisfree/2011/nov/10/small-is-beautiful-economic-idea
- Carlos Maynor Salinas Santano. (n.d.). Innovación abierta de Henry Chesbrough. Retrieved June 28, 2021, from https://www.youtube.com/watch?v=6PCv24SQ1CQ
- Charles Haycock. (2013, March 28). The Summit Documentary. https://www.youtube.com/watch?v=1EJmGyXNvsw
- ChicaGeek. (2018, March 5). Qué es IFTTT y cómo funciona. https://www.youtube.com/watch?v=lLMJRA8vkyc
- Čiutienė, R., & Thattakath, E. W. (2014). Influence of Dynamic Capabilities in Creating Disruptive Innovation. Economics and Business, 26(0), 15–21. https://doi.org/10.7250/eb.2014.015
- Cooke, R. (2020, February 17). Wikipedia Is the Last Best Place on the Internet. Wired. https://www.wired.com/story/wikipedia-online-encyclopedia-best-place-internet/
- Cordoba, C. (2015). Fundamentos del pensamiento en diseño. Revista Investigium IRE Ciencias Sociales y Humanas, 6(2), 38–50.
- Cross, N., Elliot, D., & Roy, R. (Eds.). (1974). Man-Made Futures: Readings in Society, Technology and Design (1st ed.). Hutchinson & Co.
- Dempwolf, C. S., Auer, J., & D’Ippolito, M. (2014). Innovation accelerators: Defining characteristics among startup assistance organizations. Small Business Administration, 1–44.
- Doctorow, C. (2019, October 2). Adversarial Interoperability. Electronic Frontier Foundation. https://www.eff.org/deeplinks/2019/10/adversarial-interoperability
- Doctorow, C. (2020, March 18). African WhatsApp Modders are the Masters of Worldwide Adversarial Interoperability. Electronic Frontier Foundation. https://www.eff.org/deeplinks/2020/03/african-whatsapp-modders-are-masters-worldwide-adversarial-interoperability
- Doorley, S., Holcomb, S., Klebahn, P., Segovia, K., & Utley, J. (2018). Design Thinking bootleg, dSchool. Institute of Design at Stanford.
- Dougherty, D. (2012). The Maker Movement. Innovations: Technology, Governance, Globalization, 7(3), 11–14. https://doi.org/10.1162/INOV_a_00135
- El poder de la innovación disruptiva. (2019, December 13). SingularityU Colombia Summit. https://singularityucolombiasummit.com/blog/el-poder-de-la-innovacion-disruptiva/
- Facultad de Arquitectura UNALMED. (2013, October 15). Insitu Fablab Unal. https://www.youtube.com/watch?v=Rnjk_f4rBsk
- France-Presse, A. (2021, February 17). Myanmar’s internet shutdown: What’s going on and will it crush dissent? The Guardian. http://www.theguardian.com/world/2021/feb/17/myanmars-internet-shutdown-whats-going-on-and-it-crush-dissent
- Frederick Van Amstel. (2019, abr). Design para a Inovação Social. https://pt.slideshare.net/usabilidoido/design-para-a-inovao-social-141088064
- Furr, N., & Dyer, J. (2014, December 31). Choose the Right Innovation Method at the Right Time. Harvard Business Review. https://hbr.org/2014/12/choose-the-right-innovation-method-at-the-right-time
- García, J. F. M. (n.d.). Innovación en modelos de negocio: La metodología de Osterwalder en la práctica. Revista MBA EAFIT, 18.
- Geels, F. W. (2005). Processes and patterns in transitions and system innovations: Refining the co-evolutionary multi-level perspective. Technological Forecasting and Social Change, 72(6), 681–696. https://doi.org/10.1016/j.techfore.2004.08.014
- Geels, F. W., & Schot, J. (2007). Typology of sociotechnical transition pathways. Research Policy, 36(3), 399–417. https://doi.org/10.1016/j.respol.2007.01.003
- Grafman, L. (2019, December 13). A Powerful Approach to Innovation and Design: Point-Positive. Medium. https://medium.com/@Lonny/point-positive-design-97a73dba6071
- Heierli, U. (2000). Enfocando en la creación de mercados como una ruta para el crecimiento de base amplia (p. 112). Swiss Agency for Development and Cooperation SDC. https://www.shareweb.ch/site/EI/Documents/HowTo/SDC%20-%20Heierli%20-%20Poverty%20Alleviation%20as%20a%20Business%20-%20The%20Market%20Creation%20Approach%20to%20Development%20-%202000%20-%20es.pdf
- Hippel, V., & A, E. (2016). Sources of Innovation (SSRN Scholarly Paper ID 2877276). Social Science Research Network. https://papers.ssrn.com/abstract=2877276
- How SuperFreakonomics Gets Climate Engineering Wrong. (n.d.). MIT Technology Review. Retrieved May 13, 2021, from https://www.technologyreview.com/2009/10/20/209027/how-superfreakonomics-gets-climate-engineering-wrong/
- Hurst, M. (2019, October 24). Creative Good: Juul and the corruption of design thinking [Blog]. Creative Good. https://creativegood.com/blog/19/juul-corruption-design-thinking.html
- Hutson, M. (2020, October 21). Why you don’t really know what you know. MIT Technology Review. https://www.technologyreview.com/2020/10/21/1009445/the-unbearable-vicariousness-of-knowledge/
- IDIN. (2016, May 20). IDIN Network en español por D-lab  Peru. https://www.youtube.com/watch?v=rb42NlQPOmo
- Iskander, N. (2018, September 5). Design Thinking Is Fundamentally Conservative and Preserves the Status Quo. Harvard Business Review. https://hbr.org/2018/09/design-thinking-is-fundamentally-conservative-and-preserves-the-status-quo
- jake, Jasso, A., & Triola, D. (2014). Las Malvinas rainwater catchment system 2014. https://www.appropedia.org/Las_Malvinas_rainwater_catchment_system_2014
- Kelley, T., & Kelley, D. (2013). Creative confidence: Unleashing the creative potential within us all. Currency.
- Kelley, T., & Littman, J. (2001). The art of innovation: Lessons in creativity from IDEO, America’s leading design firm (1st ed). Currency/Doubleday.
- Klaster LifeScience Kraków. (n.d.). Open Innovation 02—What is “open innovation"? Retrieved June 28, 2021, from https://www.youtube.com/watch?v=A8Bp-WEndww
- Levy, S. (n.d.). First Alan Adler Invented the Aerobie. Now He’s Created the Perfect Cup of Coffee. Wired. Retrieved July 12, 2021, from https://www.wired.com/2015/03/first-alan-adler-invented-the-aerobie-now-hes-created-the-perfect-cup-of-coffee/
- Lonny Grafman. (n.d.). Communities Empowering Communities. Retrieved June 28, 2021, from https://www.youtube.com/watch?v=TOM1WUEVUl4&list=PL9jxY7ZAs5RA_ByLak4vec7IpI1CcFuaY
- Mauzy, J., & Harriman, R. A. (2003). Creativity, Inc. Harvard Business School Press Boston, MA.
- ObservatorioTecnologíaUNED. (n.d.). Innovación abierta: ¿Qué es innovación? Retrieved June 28, 2021, from https://www.youtube.com/watch?v=JSisN7ovY94
- Oroza, E. (n.d.). Objects of necessity. Ernesto Oroza. Retrieved May 12, 2021, from http://www.ernestooroza.com/tag/objects-of-necessity/
- Osterwalder, A. (n.d.). The business model ontology a proposition in a design science approach. https://doi.org/10.22005/bcu.15985
- Plattner, H. (2018). Guía del proceso creativo. Mini guía: Una introducción al Design Thinking+ Bootcamp bootleg (F. González, Trans.).
- PNUD El Salvador. (2021, February 3). El ciclo de aprendizaje de los Laboratorios de Aceleración del PNUD. https://www.youtube.com/watch?v=E8MjWRNK46Q
- Richard Montañez, el mexicano que inventó los “Cheetos Flamin” Hot’. (n.d.). Retrieved January 24, 2021, from https://www.milenio.com/virales/cheetos-richard-montanez-mexicano-invento-flamin-hot
- Rittel, H. W. J., & Webber, M. M. (1973). Dilemmas in a general theory of planning. Policy Sciences, 4(2), 155–169. https://doi.org/10.1007/BF01405730
- Rotman, D. (n.d.). Covid-19 has blown apart the myth of Silicon Valley innovation. MIT Technology Review. Retrieved February 5, 2021, from https://www.technologyreview.com/2020/04/25/1000563/covid-19-has-killed-the-myth-of-silicon-valley-innovation/
- Sawyer, R. K. (2011). Explaining creativity: The science of human innovation. Oxford university press.
- Schot, J., Steinmueller, E., Kanger, L., & Alasoni, T. (n.d.). The three frames of innovation. University of Sussex. Retrieved May 8, 2021, from http://www.tipconsortium.net/wp-content/uploads/2019/06/4173_TIPC_3frames-3.pdf
- Stanton—Minutes, A., & Stanton—Minutes, A. (2021, January 24). Do these 5 things and you’ll never run out of new ideas. Fast Company. https://www.fastcompany.com/90597174/do-these-5-things-and-youll-never-run-out-of-new-ideas
- Taylor, L. (2020). There’s an app for that: Technological solutionism as COVID-19 policy in the Global North. SocArXiv. https://doi.org/10.31235/osf.io/grwsk
- TED. (n.d.). Yochai Benkler: Open-source economics. Retrieved June 28, 2021, from https://www.youtube.com/watch?v=NgYE75gkzkM
- TEDxYouth. (2013, December 14). A Better Education: Lonny Grafman at TEDxYouth@HumboldtBay. https://www.youtube.com/watch?v=pc3C6OwfhOE
- The Double Diamond: 15 years on | Design Council. (n.d.). Retrieved January 26, 2021, from https://www.designcouncil.org.uk/news-opinion/double-diamond-15-years
- Toyama, K. (2010, December). Boston Review—Kentaro Toyama: Can Technology End Poverty? https://bostonreview.net/archives/BR35.6/toyama.php
- Tutela de Derechos Humanos del Arzobispado de San Salvador. (n.d.). Situación actual del agua en El Salvador. Retrieved February 19, 2021, from http://tuteladh.org/sitioweb/situacion-actual-del-agua-en-el-salvador/
- Ubiquity staff. (2003). Building an inventive organization. Ubiquity, 2003(June), 1. https://doi.org/10.1145/782795.782796
- Using Emergence To Take Social Innovations To Scale – Margaret J. Wheatley. (n.d.). Retrieved February 5, 2021, from https://margaretwheatley.com/library/articles/using-emergence-take-social-innovations-scale/
- Van Amstel, F., Gonzatto, R. F., Junges, E., Costa, R., Veloso, D., da Cruz Costa, K., Marins, P., Giuliano, R., Chuves, V., Fuchs, F., Ferraz, G., & Rückert, A. (2012). Diseño Libre (E. Velis, P. Álvarez, J. Soto Galindo, S. Henríquez, I. Sol, R. Flores, S. Burgos, & D. Palacios, Trans.; 1st ed.). Instituto Faber-Ludens. https://dubsnipe.github.io/disenolibre/
- Visser, W. (2020). Integrated Innovation: Applying Systems Thinking to Sustainable Innovation and Transformation. Sustainability, 12(13), 5247.
- Von Hippel, E. (2016). Free innovation. The MIT Press.
- We Don’t Need No Innovation. (n.d.). Logic Magazine. Retrieved October 20, 2021, from https://logicmag.io/kids/we-dont-need-no-innovation/
- What Is Disruptive Innovation? (2015, December 1). Harvard Business Review. https://hbr.org/2015/12/what-is-disruptive-innovation
- Xu, G., Hu, W., Qiao, Y., & Zhou, Y. (2020). Mapping an innovation ecosystem using network clustering and community identification: A multi-layered framework. Scientometrics, 124, 2057–2081.
- Yoo, C. S. (2019). Rethinking Copyright and Personhood. University of Illinois Law Review, 2019(423), 41.


## Esquema metodológico

Esta sección contiene una descripción de mi proceso de diseño para esta clase, más allá del programa de estudio. Está basado en la metodología de _backwards design_ (diseño al revés) planteado por Wiggns et al. (2015)^[Wiggins, G. P., Wiggins, G., & McTighe, J. (2005). Understanding by design. Ascd.] 

### Etapa 1: Resultados esperados

Al finalizar este curso, el alumno:
- *O1*: Conocerá la definición y fundamentos teóricos para identificar la innovación desde un enfoque multidimensional que considere aspectos económicos, sociales, culturales y ambientales.
- *O2*: Identificará cómo las personas, las organizaciones y las sociedades accionan la innovación en diferentes campos de investigación, mercados y en la solución a problemas del desarrollo y la transformación de sistemas.
- *O3*: Aplicará técnicas y herramientas de innovación para el diseño de negocios o iniciativas de impacto social.

Las preguntas esenciales a considerarse son:
- ¿Qué es innovación y qué no es innovación?
- ¿En qué difieren las definiciones de innovación en la literatura?
- ¿Por qué es relevante la innovación para los individuos, organizaciones y sociedad?
- ¿Qué habilidades técnicas sirven para innovar?
- ¿Cómo propiciar un entorno apto para la innovación?
- ¿Es posible aumentar el potencial innovador de una idea?
- ¿Cuáles son los retos prácticos al desarrollar la innovación?
- ¿Cómo evaluar y autoevaluar la innovación?

Las comprensiones deseadas al final del curso son:
- Una visión multidimensional de la innovación.
- Una postura crítica hacia el solucionismo a partir de ejemplos de innovación no tecnológicos, innovaciones de base, conocimiento ancestral y otros saberes con aplicaciones innovadoras.
- La diferencia entre innovación y otros conceptos que crean confusión tales como: creatividad, tecnología, propuesta de valor y novedad.
- Qué herramientas metodológicas utilizan los expertos para generar y evaluar las innovaciones a nivel individual y organizacional.
- Las estructuras organizacionales y colaborativas a nivel global que permiten la innovación.
- El potencial de la innovación en los ámbitos de gobierno, de negocios y de impacto social.
- Las similitudes y diferencias entre innovación y el éxito comercial en una propuesta.
- Las habilidades técnicas e interpersonales puede cultivar el estudiante para desarrollar innovación en el futuro.
- La relación entre las propuesta de valor y la innovación en un modelo de negocios.

Los estudiantes desarrollarán los siguientes conocimientos y habilidades:
- Los siguientes conceptos clave: problemas enredados, innovación, innovación integrada, ecosistema de innovación, aceleración e incubación, tecnología, propuesta de valor, diseño centrado en las personas y solucionismo tecnológico.
- Una contextualización de la innovación al contexto global, regional y nacional.
- La capacidad de identificar actores y sus acciones en los ecosistemas de innovación.
- Una noción básica de las maneras en las que las innovaciones impactan las sociedades.
- La habilidad de realizar una revisión bibliográfica sobre aspectos técnicos como métodos, herramientas y tecnologías.
- La capacidad de realizar una crítica a una propuesta de innovación a partir de la investigación y la aplicación de su criterio personal orientado a su contexto personal.

### Etapa 2: Evidencias de aprendizaje

- R1
  - Los estudiantes serán capaces de plantear una definición personal de la innovación que demuestre la comprensión de (1) las ideas y definiciones planteadas en clase, (2) vídeos con definiciones planteadas por expertos en tecnología e innovación y (3) la lectura de al menos un artículo que define la innovación integrada.^[Visser, W. (2020). Integrated Innovation: Applying Systems Thinking to Sustainable Innovation and Transformation. Sustainability, 12(13), 5247.
]
  - Los estudiantes serán capaces de plantear similitudes y divergencias entre las definiciones y expresar su postura personal con respecto al concepto de innovación.
  - Los estudiantes podrán identificar los "hitos de la innovación" en la historia de un ámbito técnico de su elección, con base en los criterios de la innovación integrada.
  - Los estudiantes serán capaces de realizar un ejercicio de prospectiva sobre el posible impacto una innovación, basados en la Tétrada de Medios de Marshall McLuhan.^[Adam, I. (2016). What Would McLuhan Say about the Smartphone? Applying McLuhan’s Tetrad to the Smartphone. Glocality, 2(1), 3. https://doi.org/10.5334/glo.9
]
- R2
  - Los estudiantes explorarán el concepto de "problemas enredados" a partir de la creación de un mapa de actores en el que se estudiarán las dimensiones ambientales, sociales y tecnológicas de los problemas.
  - *Examen*: Se explorará la creación de valor integrado a partir de un mapa de actores y una propuesta de valor con la capacidad de generar deseabilidad a cada uno de ellos.
  - Se hará un repaso de herramientas como el Business Model Canvas, Value Proposition Canvas y otros con un enfoque orientado a la innovación integrada.
  - Se elaborará una revisión bibliográfica formal (con referencias en formato APA) sobre un tipo de innovación para comparar los abordajes de cada una con respecto a criterios de la innovación integrada.
- R3
  - Los estudiantes desarrollarán un producto multimedia (podcast, reel o blog) enfocado en uno de los Objetivos de Desarrollo Sostenible.
  - Para el proyecto final, los estudiantes evaluarán una propuesta tecnológica para la creación de una propuesta de innovación, documentada y justificada, a partir de una propuesta de valor que mejore el alcance original de la solución original.
  - Los estudiantes son capaces de defender sus propuestas de innovación del proyecto final.

### Etapa 3—Plan de aprendizaje
Las clases se desarrollarán por medio del siguiente formato:

- Clase 1 (asincrónica): 
  - Una discusión del tema principal por medio de un vídeo de aproximadamente 15 minutos.
  - Se planteará una guía de preguntas para responder por medio de los recursos (lecturas, vídeos, etc.).
  - La guía podrá ser utilizada como base para la evaluación por medio de Moodle.
- Clase 2:
  - La clase planteará las preguntas de la guía semanal como punto de partida para la discusión. Las respuestas servirán para la evaluación de la nota de participación.
- Clase 3:
  - La tercera clásica servirá para el dearrollo de una actividad práctica grupal con un componente de discusión. Se evaluará la entrega de las actividades al final de la clase.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```